### ISSUE TITLE
Review security module

### ISSUE THREAD

**Issue by Trehinos** [Trehinos/Thor#36]
Example of future ```security.yml``` :

```yaml
security: enable | [disable]
identity-source: database | ldap | file | [internal] # ldap: identity-type=user only
identity-type: token | both | [username-password]

# if identity-source === database
database-pdo-row: ~ # implements UserInterface & PdoRowInterface

# if identity-source === file
file-name: ~
file-fields: ~
file-separator: ~
file-php-structure: ~

# if user-source === ldap
ldap-host: ~
ldap-user: ~
ldap-password: ~

authentication: '[session] | header_token'
# if authentication === header_token
authentication-key: ~
authentication-expire: ~

# option : firewall, protect routes
firewall:
    -   pattern: /
        redirect: ~ # public page to redirect if a status_forbidden is triggered
        login-route: login
        logout-route: logout
        check-route: check
        exclude-path:
            - ''
            - ''
```
